#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"

# This wizard reads values you type. Without a real terminal every prompt
# returns empty and it would silently write blank credentials.
if [[ ! -t 0 ]]; then
  printf '\n  %s⚠ This wizard needs an interactive terminal.%s\n\n' "$YELLOW" "$RESET"
  printf '  Open Terminal (or iTerm), then run:\n\n'
  printf '      cd %s\n      ./deploy.sh\n\n' "$(pwd)"
  printf '  %sRunning it through a non-interactive shell cannot capture what you type.%s\n\n' "$DIM" "$RESET"
  exit 1
fi

banner "GTask — Supabase + Vercel deploy"

# ── 1. Supabase project ───────────────────────────────────────────────────
stage "Supabase: create the project"
say "GTask stores every finished check in one Supabase table."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project'."
step "Name it 'gtask', pick the region closest to your users, set a database password."
step "Wait until the project finishes provisioning (about a minute)."
pause "Press Enter once the project is ready."

# ── 2. The table ──────────────────────────────────────────────────────────
stage "Supabase: create the submissions table"
say "The schema lives in supabase/schema.sql — one table, RLS on, no anon policy."
if command -v pbcopy >/dev/null 2>&1; then
  pbcopy < supabase/schema.sql
  note "schema.sql is now on your clipboard"
elif command -v xclip >/dev/null 2>&1; then
  xclip -selection clipboard < supabase/schema.sql
  note "schema.sql is now on your clipboard"
else
  warn "no clipboard tool found — open supabase/schema.sql and copy it by hand"
fi
open_url "https://supabase.com/dashboard/project/_/sql/new"
step "Pick your gtask project if asked, paste the SQL, then press 'Run'."
step "You should see 'Success. No rows returned'."
pause "Press Enter once the table is created."

# ── 3. Credentials ────────────────────────────────────────────────────────
stage "Supabase: API credentials"
say "Two values: the project URL and the service-role key."
warn "The service-role key bypasses row-level security. It stays on the server — never in client code, never in git."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Copy 'Project URL' (looks like https://abcdefgh.supabase.co)."
ask SUPABASE_URL "Paste the project URL:"
step "Under 'Project API keys', reveal the 'service_role' key and copy it."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the service_role key (hidden):"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

say ""
say "Checking the connection with a real insert…"
if node scripts/verify-supabase.mjs; then
  printf '  %s✓ Supabase is ready%s\n' "$GREEN" "$RESET"
else
  warn "That did not work. Check the URL and key, and that the SQL ran, then re-run this wizard."
  exit 1
fi
pause

# ── 4. Vercel account ─────────────────────────────────────────────────────
stage "Vercel: sign in"
say "The deploy runs through the Vercel CLI, using npx so nothing is installed globally."
if npx --yes vercel@latest whoami >/dev/null 2>&1; then
  note "already signed in as $(npx --yes vercel@latest whoami 2>/dev/null)"
else
  step "A browser window will open — sign in with the account you want to deploy under."
  npx --yes vercel@latest login
fi
pause

# ── 5. Link and configure ─────────────────────────────────────────────────
stage "Vercel: link the project and push the environment"
say "Linking creates (or attaches to) a Vercel project for this folder."
npx --yes vercel@latest link --yes --project gtask
for key in SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY; do
  value=$(grep -E "^${key}=" "$ENV_FILE" | tail -n1); value="${value#*=}"
  for env in production preview development; do
    npx --yes vercel@latest env rm "$key" "$env" --yes >/dev/null 2>&1 || true
    printf '%s' "$value" | npx --yes vercel@latest env add "$key" "$env" >/dev/null 2>&1 \
      && printf '  %s✓ set%s %s (%s)\n' "$GREEN" "$RESET" "$key" "$env"
  done
done
pause

# ── 6. Deploy ─────────────────────────────────────────────────────────────
stage "Vercel: deploy to production"
confirm "Deploy to production now?" || { warn "stopped before deploying"; finish; exit 0; }
DEPLOY_URL=$(npx --yes vercel@latest deploy --prod | tail -n1)
say ""
printf '  %s✓ live at%s %s\n' "$GREEN" "$RESET" "$DEPLOY_URL"
write_env NEXT_PUBLIC_SITE_URL "$DEPLOY_URL"
for env in production preview development; do
  npx --yes vercel@latest env rm NEXT_PUBLIC_SITE_URL "$env" --yes >/dev/null 2>&1 || true
  printf '%s' "$DEPLOY_URL" | npx --yes vercel@latest env add NEXT_PUBLIC_SITE_URL "$env" >/dev/null 2>&1 || true
done
note "open the site, finish a check, and the row appears in the Supabase table editor"

finish
