import { chromium } from 'playwright';
const theme = process.env.T ?? 'light';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, colorScheme: theme });
await ctx.addInitScript((t) => localStorage.setItem('gtask-theme', t), theme);
const p = await ctx.newPage();
await p.goto('http://localhost:3000/check', { waitUntil: 'networkidle' });
await p.waitForTimeout(900);
await p.locator('button[aria-pressed]').nth(1).hover();
await p.waitForTimeout(500);
await p.screenshot({ path: `shots/sec/check-hover-${theme}.png` });
console.log('ok');
await b.close();
